server:
  port: 8080

spring:
  application:
    name: financial_app
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/trinity_financial_app?useSSL=false&serverTimeZone=UTC&allPublicKeyRetrival=true
    username: root
    password: root2904
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: show
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  pattern:
    dateformat: hh:mm
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE